#' DESCRIPTION:
#' S09: Calculates site-level biodiversity metrics and performs fixed-effect
#' regression (fixest::feols) across METSO stands and matched BAU/control groups.
#' 
#' METHODOLOGY:
#' - Modes: Posterior mean ("mean"), n draws ("draws"), or all draws ("all").
#' - Aggregation: Averages pairwise comparisons against group controls in-memory.
#' - Parallelism: Distributes METSO stand chunks per group across CPU cores.
#' - Statistical Modeling: Evaluates treatment elasticity via fixed-effects OLS.
#' 
#' INPUTS:
#' - Model Metadata: models/unfitted_RData/unfitted_[model_id].RData
#' - Traits Data: data/traits/TrData_complete.rds
#' - Group Matches: results/matched_pairs_groups_metso.rds & _control.rds
#' - Predictions: results/predictions/ & results/predictions_PA/ (Arrow partition)
#' 
#' OUTPUTS:
#' - Group Parquet files: results/metrics/[expected_type]/metrics_group_[N].parquet

library(tidyverse)
library(Hmsc)
library(parallel)
library(here)
library(arrow)
library(data.table)
library(FD)

source(file.path("code", "_utilities_diversity_metrics_functions.R"))
source(file.path("code", "config_model.R"))
name_model <- generate_run_name(run_config)

message("    Start time: ", Sys.time())

# --- Configuration ---
# Modes: "draws" (testing/dev), "all" (final analysis). Legacy "mean" disabled.
run_mode <- "draws"
n_draws  <- 100
seed     <- 11072024
set.seed(seed)

# Prevent running legacy 'mean' mode for production
if (run_mode == "mean") {
  stop("Legacy 'mean' mode is disabled for production to avoid metric bias (e.g. FRic). Use 'draws' or 'all'.")
}

selected_draws <- NULL
if (run_mode == "draws") {
  selected_draws <- sort(sample.int(4000, n_draws))
}

# Execution mode flag: set to FALSE Set to FALSE for full run
test <- FALSE

# Expected abundance predictions vs stochastic realizations (draws from distribution)
expected_string <- "_expected_true"

os <- Sys.info()['sysname']
if (os == "Windows") {
  n_cores <- max(1, floor(parallel::detectCores() / 2))
  wr_dir <- "results"
} else if (os %in% c("Linux", "Darwin")) {
  
  n_cores <- min(32, floor(parallel::detectCores() / 2))
  node <- Sys.info()["nodename"]
  
  if (node == "lema") {
    wr_dir <- NULL
    worker_tmp <- NULL
  } else if(node == "gurnah"){
    wr_dir <- "/export/scratch/tmp/munozcs/results"
  } else {
    wr_dir <- NULL # here::here("results")
  }
}

output_dir <- if (test) {
  file.path(wr_dir, "metrics", "test", expected_string, run_mode)
} else {
  file.path(wr_dir, "metrics", expected_string, run_mode)
}
if (!dir.exists(output_dir)) dir.create(output_dir, recursive = TRUE)


# 1. Load Species and Traits
load(file.path("models", "unfitted_RData", paste0("unfitted_", run_config$model_id, ".RData")))
name_spp <- colnames(models$fbs_M016$Y)

tr_proc_file <- file.path(wr_dir, "metrics", "TrData_processed.rds")
if (!file.exists(tr_proc_file)) {
  cat("----- Calculating TrData processing...\n")
  TrData <- readRDS(file.path("data", "traits", "TrData_complete.rds"))
  rownames(TrData) <- name_spp
  TrData_numeric <- TrData |> 
    select(where(is.numeric), -any_of(c("Total.individuals", "Female", "Male", "Unknown", "Complete.measures")))
  
  dummy_a <- matrix(1, nrow = 1, ncol = length(name_spp))
  colnames(dummy_a) <- name_spp
  
  TrData_processed <- dbFD_preprocess_traits(x = TrData_numeric, a = dummy_a)
  saveRDS(TrData_processed, tr_proc_file)
} else {
  TrData_processed <- readRDS(tr_proc_file)
}

cum_var <- cumsum(TrData_processed$eigenvalues) / sum(TrData_processed$eigenvalues) * 100
TrData_processed$traits.FRic <- TrData_processed$traits.FRic[, cum_var <= 95]
divmax <- ade4::divcmax(as.dist(TrData_processed$x.dist))$value

# 2. Prepare match and arrow connection
# Load and bind the group match metadata generated by S08b
matches_metso <- readRDS(file.path(wr_dir, "matched_pairs_groups_metso.rds"))
matches_control <- readRDS(file.path(wr_dir, "matched_pairs_groups_control.rds"))
groups_df <- bind_rows(matches_metso, matches_control)

# Ensure common group numbers between treated and control
common_groups <- intersect(
  unique(groups_df$group_number[groups_df$metso == 1]),
  unique(groups_df$group_number[groups_df$metso == 0])
)

if (test) {
  test_group_file <- file.path(wr_dir, "test_group_stands.rds")
  
  if (file.exists(test_group_file)) {
    cat("Loading pre-defined test strata from test_group_stands.rds...\n")
    test_meta <- readRDS(test_group_file)
    
    # Filter common groups to those present in the test group cache
    common_groups <- intersect(common_groups, unique(test_meta$group_number))
  } else {
    cat("Selecting small strata groups directly from groups_df...\n")
    # Identify groups with at least 5 but at most 50 stands in both METSO and control
    max_stands_per_scenario <- 50
    small_groups <- groups_df |>
      filter(group_number %in% common_groups) |>
      group_by(group_number, metso) |>
      summarise(n_stands = n(), .groups = "drop") |>
      pivot_wider(names_from = metso, values_from = n_stands, names_prefix = "m_") |>
      filter(
        m_1 >= 5 & m_1 <= max_stands_per_scenario,
        m_0 >= 5 & m_0 <= max_stands_per_scenario
      ) |>
      pull(group_number)
    
    common_groups <- head(small_groups, 10) # Take 5 lightweight groups
  }
  
  cat(sprintf("Test: processing %d lightweight groups.\n", length(common_groups)))
}

# Hurdle predictions
predY_ds <- open_dataset(
  file.path(wr_dir, "predictions"), 
  hive_style = TRUE, 
  unify_schemas = TRUE
) |> 
  filter(
    modelid == run_config$model_id, 
    expected_type == expected_string
  )

# Parallel PA probability predictions
predPA_ds <- open_dataset(
  file.path(wr_dir, "predictions_PA"), 
  hive_style = TRUE, 
  unify_schemas = TRUE
) |> 
  filter(
    modelid == run_config$model_id, 
    expected_type == expected_string
  )

# 3. Helper Functions
prepare_stand_matrix <- function(sub_df, mode, n_target, cols_drop, selected_draws = NULL) {
  sub_df <- sub_df[order(sub_df$posterior), ]
  mat <- as.matrix(sub_df[, !(names(sub_df) %in% cols_drop)])
  
  # Legacy branch retained for history; production should use 'draws' or 'all'
  if (mode == "mean") {
    mat_eval  <- matrix(colMeans(mat, na.rm = TRUE), nrow = 1)
    colnames(mat_eval) <- colnames(mat)
    
    return(list(mat = mat_eval, draws = "mean"))
  } else if (mode == "draws") {
    if (is.null(selected_draws)) {
      avail <- unique(sub_df$posterior)
      selected_draws <- sort(sample(avail, min(n_target, length(avail))))
    }
    mat_eval <- mat[sub_df$posterior %in% selected_draws, , drop = FALSE]
    return(list(mat = mat_eval, draws = selected_draws))
  } else {
    return(list(mat = mat, draws = sub_df$posterior))
  }
}

process_metso_slice_averaged <- function(metso_sub_ids, metso_precomputed, control_precomputed, g_id, n_post, draw_names) {
  metso_results <- list()
  counter <- 1
  
  for (m_id in metso_sub_ids) {
    # m_id <- "38418827_2019"
    prep_m <- metso_precomputed[[as.character(m_id)]]
    if (is.null(prep_m)) next
    
    pair_collector <- list()
    p_counter <- 1
    
    for (c_id in names(control_precomputed)) {
      # c_id <- "6773141_2019"
      prep_c <- control_precomputed[[c_id]]
      if (is.null(prep_c)) next
      
      res_df <- tryCatch({
        calculate_pairwise_metrics_fast(
          metso_prep = prep_m,
          bau_prep = prep_c,
          num_posteriors = n_post
        )
      }, error = function(e) return(NULL))
      
      if (!is.null(res_df)) {
        pair_collector[[p_counter]] <- res_df
        p_counter <- p_counter + 1
      }
    }
    
    if (length(pair_collector) > 0) {
      combined_dt <- data.table::rbindlist(pair_collector)
      
      if (length(draw_names) == n_post && !identical(draw_names, "mean")) {
        draw_map <- data.table(posterior = seq_len(n_post), actual_draw = draw_names)
        combined_dt <- merge(combined_dt, draw_map, by = "posterior")
        combined_dt[, posterior := actual_draw][, actual_draw := NULL]
      }
      
      summary_dt <- combined_dt[, .(
        val_mean = mean(val, na.rm = TRUE),
        val_sd   = if (.N > 1) sd(val, na.rm = TRUE) else 0.0,
        n_controls = .N
      ), by = .(posterior, metrics)]
      
      summary_dt[, standid_treated := m_id]
      summary_dt[, group_number := g_id]
      
      metso_results[[counter]] <- summary_dt
      counter <- counter + 1
    }
  }
  
  if (length(metso_results) > 0) return(data.table::rbindlist(metso_results))
  return(NULL)
}

# 4. Processing Loop
cols_drop <- c("scenario", "standid", "posterior", "year", "reg", "trees")

for (g_id in common_groups) {
  # g_id <- common_groups[9]
  out_file <- file.path(output_dir, paste0("metrics_group_", g_id, ".parquet"))
  if (file.exists(out_file)) {
    cat(sprintf("Group %s already processed. Skipping.\n", g_id))
    next
  }
  
  group_stands <- groups_df[groups_df$group_number == g_id, ]
  # zeros on fric
  # group_stands <- group_stands |>  dplyr::filter(standid %in% c("38418827_2019", "38553528_2019", "38713591_2019") | metso == 0)
  metso_ids <- group_stands$standid[group_stands$metso == 1]
  control_ids <- group_stands$standid[group_stands$metso == 0]
  if (length(metso_ids) == 0 || length(control_ids) == 0) next
  
  g_year  <- group_stands$year[1]
  g_reg   <- group_stands$reg[1]
  g_trees <- group_stands$trees[1]
  
  group_preds <- predY_ds |> 
    filter(
      year == g_year,
      reg == g_reg,
      trees == g_trees,
      standid %in% group_stands$standid
    ) |> 
    select(scenario, standid, posterior, all_of(name_spp)) |> 
    collect()
  
  group_pa <- predPA_ds |> 
    filter(
      year == g_year,
      reg == g_reg,
      trees == g_trees,
      standid %in% group_stands$standid
    ) |> 
    select(scenario, standid, posterior, all_of(name_spp)) |> 
    collect()
  
  if (run_mode == "draws") {
    group_preds <- group_preds |> filter(posterior %in% selected_draws)
    group_pa    <- group_pa |> filter(posterior %in% selected_draws)
  }
  
  group_preds_dt <- data.table::as.data.table(group_preds)
  data.table::setkeyv(group_preds_dt, c("scenario", "standid", "posterior"))
  
  group_pa_dt <- data.table::as.data.table(group_pa)
  data.table::setkeyv(group_pa_dt, c("scenario", "standid", "posterior"))
  
  stands_manifest <- rbind(
    data.table::data.table(standid = metso_ids, scenario = "metso"),
    data.table::data.table(standid = control_ids, scenario = "control")
  )
  
  stand_items <- split(stands_manifest, seq_len(nrow(stands_manifest)))
  
  precomputed_results <- parallel::mclapply(
    X = stand_items,
    FUN = function(item) {
      # item <- stand_items[[1]]
      st_id <- item$standid
      scen  <- item$scenario
      
      # Fast keyed lookup using data.table
      p_sub  <- group_preds_dt[.(scen, st_id), nomatch = NULL]
      pa_sub <- group_pa_dt[.(scen, st_id), nomatch = NULL]
      if (nrow(p_sub) == 0 || nrow(pa_sub) == 0) return(NULL)
      
      prep_hurdle <- prepare_stand_matrix(as.data.frame(p_sub), run_mode, n_draws, cols_drop, selected_draws)
      prep_pa     <- prepare_stand_matrix(as.data.frame(pa_sub), run_mode, n_draws, cols_drop, selected_draws)
      metrics     <- precalculate_stand_metrics(prep_hurdle$mat, prep_pa$mat, TrData_processed, divmax)
      
      list(
        standid = as.character(st_id),
        scenario = scen,
        metrics = metrics
      )
    },
    mc.cores = n_cores
  )
  
  metso_precomputed <- list()
  control_precomputed <- list()
  
  for (res in precomputed_results) {
    if (is.null(res)) next
    if (res$scenario == "metso") {
      metso_precomputed[[res$standid]] <- res$metrics
    } else {
      control_precomputed[[res$standid]] <- res$metrics
    }
  }
  
  valid_metso_ids <- names(metso_precomputed)
  valid_control_ids <- names(control_precomputed)
  
  if (length(valid_metso_ids) == 0 || length(valid_control_ids) == 0) {
    cat(sprintf("Group %s missing valid prediction records across scenarios. Skipping.\n", g_id))
    next
  }
  
  n_post <- nrow(metso_precomputed[[1]]$pred_mat)
  draw_names <- if (run_mode == "mean") "mean" else if (run_mode == "draws") selected_draws else seq_len(n_post)
  
  chunk_size <- ceiling(length(valid_metso_ids) / n_cores)
  metso_slices <- split(valid_metso_ids, ceiling(seq_along(valid_metso_ids) / chunk_size))
  
  results <- parallel::mclapply(
    X = metso_slices,
    FUN = function(slice) {
      # slice <- metso_slices[[1]]
      process_metso_slice_averaged(
        metso_sub_ids     = slice,
        metso_precomputed = metso_precomputed,
        control_precomputed = control_precomputed,
        g_id              = g_id,
        n_post            = n_post,
        draw_names        = draw_names
      )
    },
    mc.cores = n_cores
  )
  
  results_dt <- data.table::rbindlist(results)
  if (nrow(results_dt) > 0) {
    arrow::write_parquet(results_dt, out_file)
    cat(sprintf("[%s] Group %s written: %d treated stands evaluated against %d controls.\n", 
                format(Sys.time(), "%H:%M:%S"), g_id, length(valid_metso_ids), length(valid_control_ids)))
  }
  
  # Memory cleaning
  rm(group_preds, group_pa, group_preds_dt, group_pa_dt, stands_manifest, stand_items, precomputed_results, 
     metso_precomputed, control_precomputed, results, results_dt)
  gc()
}

message("    End time: ", Sys.time())